"""empty message

Revision ID: 118f56bd5caf
Revises: f80b1919c3d8
Create Date: 2018-07-05 17:25:01.647555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '118f56bd5caf'
down_revision = 'f80b1919c3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('article_attachmets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_attachmets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('attachment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('heading', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('sub_heading', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
