"""empty message

Revision ID: f80b1919c3d8
Revises: 3b3b54119c50
Create Date: 2018-07-05 12:11:12.082120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80b1919c3d8'
down_revision = '3b3b54119c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_attachmets', sa.Column('article_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_attachmets', 'article_id')
    # ### end Alembic commands ###
